-- require('avante').setup({
--     provider = "copilot",
--     auto_suggestions_provider = nil,
--     copilot = {
--         model = "claude-3.5-sonnet",
--         endpoint = "https://api.githubcopilot.com",
--         allow_insecure = false,
--         timeout = 10 * 60 * 1000,
--         temperature = 0,
--         max_completion_tokens = 1000000,
--         reasoning_effort = "high",
--     },
--     behaviour = {
--         auto_suggestions = false, -- Experimental stage
--         auto_set_highlight_group = true,
--         auto_set_keymaps = false,
--         auto_apply_diff_after_generation = false,
--         support_paste_from_clipboard = false,
--         minimize_diff = true, -- Whether to remove unchanged lines when applying a code block
--         enable_token_counting = false,
--         enable_cursor_planning_mode = false,
--         enable_claude_text_editor_tool_mode = false, -- Whether to enable Claude Text Editor Tool Mode.
--     },
--     hints = { enabled = false },
-- })
