#!/usr/bin/env bash
#
# Author: Devon Morris <devonmorris1992@gmail.com>
#
# Build a docker dev environment for ROS2
# TODO: need to handle annoying versioning things for support ROS1 too
set -euo pipefail

function exists_in_list() {
    LIST=$1
    DELIMITER=$2
    VALUE=$3
    echo $LIST | tr "$DELIMITER" '\n' | grep -F -q -x "$VALUE"
}

ROS1_VERSIONS="kinetic melodic noetic"
if exists_in_list "$ROS1_VERSIONS" " " "${@: -1}";
then
  ROS_VERSION="1"
else
  ROS_VERSION="2"
fi


ROS_DISTRO="${@: -1}"
ROS_DISTRO_IMAGE="ros:${ROS_DISTRO}-perception"

if [[ "$ROS_VERSION" == "1" ]];
then
APT_DEPS="ros-${ROS_DISTRO}-rqt-graph ros-${ROS_DISTRO}-rviz"
else
APT_DEPS="ros-${ROS_DISTRO}-rqt-graph ros-${ROS_DISTRO}-rviz2"
fi

# Remove final entry from parameters
set -- "${@:1:$(($#-1))}"
export APT_DEPS
build-docker-dev $@ $ROS_DISTRO_IMAGE
