#!/usr/bin/env bash
#
# Author: Devon Morris <devonmorris1992@gmail.com>
#
# Run a docker container and volume in home directory for configs
set -euo pipefail

WORKSPACE="$PWD"
NET="host"

function run() {
  docker run -it \
    -e "TERM=xterm-256color" \
    -e "DISPLAY=$DISPLAY" \
    -v "/etc/localtime:/etc/localtime:ro" \
    -v "/tmp/.X11-unix:/tmp/.X11-unix" \
    -v "$HOME:$HOME" \
    -w "$WORKSPACE" \
    --privileged \
    --network "${NET}" \
    $@
}

VALID_ARGS=$(getopt -o n: --long net: -- "$@")
if [[ $? -ne 0 ]]; then
    exit 1;
fi

eval set -- "$VALID_ARGS"
while [ : ]; do
  case "$1" in
    -n | --net)
        NET="$2"
        if [[ "$NET" == "compose" ]];
        then
          NET="$(basename $PWD)_default"
        fi
        shift 2
        ;;
    --) shift;
        break
        ;;
  esac
done

run $@
