#!/usr/bin/env bash

PRG=${1:-"spotify"}
VOL=${2:-"+5%"}

SRC=$(pacmd list-sink-inputs | tr '\n' '\r' |
perl -pe 's/ *index: ([0-9]+).+?application\.name = "([^\r]+)"\r.+?(?=index:|$)/\2:\1\r/g' |
tr '\r' '\n' |
grep -i $PRG | cut -d":" -f2-)

pactl set-sink-input-volume $SRC $VOL
