#!/usr/bin/env bash

dwm_resources () {
    # Used and total memory
    MEMUSED=$(free --mega | awk '(NR == 2) {print $3}')
    MEMTOT=$(free --mega |awk '(NR == 2) {print $2}')
    # CPU temperature
    CPU=$(sysctl -n hw.sensors.cpu0.temp0 | cut -d. -f1)
    # Used and total storage in /home (rounded to 1024B)
    STOUSED=$(df -h | grep '/sda' | awk '{print $3}')
    STOPER=$(df -h | grep '/sda' | awk '{print $5}')

    printf "%s" "$SEP1"
    printf "Mem %s/%s Storage %s/%s: %s" "$MEMUSED" "$MEMTOT" "$STOUSED" "$STOTOT" "$STOPER"
    printf "%s\n" "$SEP2"
}

dwm_battery () {
    # Change BAT1 to whatever your battery is identified as. Typically BAT0 or BAT1
    CHARGE=$(cat /sys/class/power_supply/BAT1/capacity)
    STATUS=$(cat /sys/class/power_supply/BAT1/status)

    printf "%s" "$SEP1"
    printf "Bat %s%% %s" "$CHARGE" "$STATUS"
    printf "%s\n" "$SEP2"
}

dwm_network () {
    CONNAME=$(nmcli -a | grep 'Wired connection' | awk 'NR==1{print $1}')
    if [ "$CONNAME" = "" ]; then
        CONNAME=$(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -c 5-)
    fi

    PRIVATE=$(nmcli -a | grep 'inet4 192' | awk '{print $2}')
    PUBLIC=$(curl -s https://ipinfo.io/ip)

    printf "%s" "$SEP1"
    printf "Net %s %s : %s" "$CONNAME" "$PRIVATE" "$PUBLIC"
    printf "%s\n" "$SEP2"
}

# This is the loop that update the bar
while true; do
  xsetroot -name "$(dwm_resources) | $(dwm_battery) | $(dwm_network) | $(date)"
  sleep 10
done
